content_dir_name: content
content_include_dir: include
num_of_entries_per_page: 5
num_of_elements_in_summary: 3
pandoc_format_md: markdown_github+footnotes+inline_notes
pandoc_format_rst: rst
resources:
  - jpg
  - png
excerpt_length: 2
